name: Build and Release

on:
  push:
    branches:
      - master
  workflow_dispatch: 

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version from file
        id: get_version
        run: |
          VERSION="$(cat modeswitchversion.txt | tr -d '\n\r')"
          UMSPATH="./usb-modeswitch-${VERSION}.tar.bz2"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "umspath=$UMSPATH" >> $GITHUB_OUTPUT
          echo "Detected version: $VERSION"

      - name: Build arm
        run: |
          cd build_with_static_linking
          chmod +x ./build_for_current_platform.sh
          ./build_for_current_platform.sh

      - name: Build x64
        run: |
          cd build_with_static_linking
          chmod +x ./build_for_x64_on_arm.sh
          ./build_for_x64_on_arm.sh
          


      - name: Verify build artifacts
        run: |
          ls -la
          if [ ! -f "./usb_modeswitch-x64" ] || [ ! -f "./usb_modeswitch-current" ]; then
            echo "ERROR: usb_modeswitch-x64 or usb_modeswitch-current files not found!"
            exit 1
          fi
          mv ./usb_modeswitch-current ./usb_modeswitch-arm64

      - name: Create Git Tag
        run: |
          VERSION="${{ steps.get_version.outputs.version }}-macos"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag $VERSION
          git push origin $VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release and Upload Artifacts
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.version }}-macos
          name: ${{ steps.get_version.outputs.version }}-macos
          body: "Statically linked binaries with libusb."
          draft: false
          prerelease: false
          files: |
            ./usb_modeswitch-x64
            ./usb_modeswitch-arm64
            ${{ steps.get_version.outputs.umspath }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
